import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <SessionProvider>
         <html lang="en" data-theme="cupcake">
            <body className={inter.className}>
               <div className="flex min-h-screen">
                  <Sidebar />
                  <main className="flex-grow">{children}</main>
               </div>
            </body>
         </html>
      </SessionProvider>
   );
}
