import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Sidebar from "@/components/pages/Sidebar";
import Back from "@/components/Back"; // Import the Back component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <SessionProvider>
         <html lang="en" data-theme="cupcake" suppressHydrationWarning>
            <body className={inter.className} suppressHydrationWarning>
               <div className="flex min-h-screen">
                  <Sidebar />
                  <main className="flex-grow relative bg-gray-900">
                     <div className="absolute top-4 left-4">
                        <Back />
                     </div>
                     {children}
                  </main>
               </div>
            </body>
         </html>
      </SessionProvider>
   );
}
